# Generated by Django 4.2.5 on 2023-09-23 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('roll', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentModelAdmin',
            fields=[
                ('studentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='first_app.studentmodel')),
            ],
            bases=('first_app.studentmodel',),
        ),
    ]
